### ISSUE TITLE
Add alliasses

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/ts-essentials#102]
Many already existing types could have more than one name. I think we should for sure add more keywords to readme to make them easily searchable but we should also consider adding aliases into packages for example:

`OmitProperties` -> `FilterProperties`

**Comment by quezak** [comment]
1. General opinion
I'm all for adding keywords and aliases to the readme, but kinda against adding them to the code.
Adding aliases to typings will confuse people and decrease code readability if different files use different aliases (either by accident, or by preferences of different devs).
As says the Zen of Python:
> There should be one -- and preferably only one -- obvious way to do it.


2. The specific example you mentioned -- I'd be strongly against aliasing `OmitProperties` with `FilterProperties`. First, the `filter` word is always ambiguous, because is not intuitive whether it _removes_ or _keeps_ the matched elements. In particular, this one is in contradiction with how `array.filter` works in JS/TS -- it keeps the matched elements, while here we omit them.

**Comment by macbem** [comment]
I agree with @quezak - I think we should create a README section with common aliases, but we shouldn't add them to the codebase. If anything, we could consider renaming some types in an upcoming major if they are often searched for under another name.

**Comment by krzkaczor** [comment]
@macbem @quezak yup, this works. This is exactly what `lodash` does - they provide keywords, aliases in docs but not in the code. It's reasonable. 

I am gonna make a PR with some first batch of aliases soon 👍
