### ISSUE TITLE
Suggestion: PickOptional and RequireOne

### ISSUE THREAD

**Issue by xenoterracide** [krzkaczor/ts-essentials#155]
The first one I'm certain is possible, basically the equivalent of this
```ts
MarkOptional<
  Pick<UserEntity, 'queueName'>,
  'queueName'
>;
```

the second I'm not so sure

```ts
RequireOne<
  Pick<UserEntity, 'queueName' | 'username'>,
  'queueName' | 'username'
>;
```
ignore the second if it's not possible

**Comment by quezak** [comment]
Looks like these could be written as simple aliases:
```typescript
type PickOptional<T, K extends keyof T> = Partial<Pick<T, K>>
type PickRequired<T, K extends keyof T> = Required<Pick<T, K>>
```

Is this what you need? 

We usually don't add such new types if they're a trivial composition of two existing ones, since you can just use the composition directly or make such an alias locally. Unless there's a good reason or added value in them, @krzkaczor what do you think?

**Comment by xenoterracide** [comment]
I think those actually will do... I don't have a more complex case at this time, I implemented with `MarkOptional` but still learning these things, sorry to waste time. I'll let you close, I'll close.
