### ISSUE TITLE
NonNever still accepts extra props 

### ISSUE THREAD

**Issue by zanona** [krzkaczor/ts-essentials#180]
When creating 'Foo' with restricted props, and 'Bar, with same properties plus a new one, 'Bar' still can be assigned as 'Foo', even though it has extra properties _(see `foo1`)_.

```ts
import type {NonNever} from 'ts-essentials';

type Foo = NonNever<{one: number; two: number}>;
type Bar = NonNever<{one: number; two: number, three: number}>;

const bar:Bar = {one: 1, two: 2, three: 3}; // OK
const foo1:Foo = bar; // Should throw exception as `bar` has additional property `three`
const foo2:Foo = {one: 1, two: 2, three: 3}; // Expected Exception - OK


console.log(bar, foo1, foo2);
```

Is this the expected behaviour or you'd recommend any workaround it?
Thanks in advance.

Playgrond link:
https://tsplay.dev/Bmxjbw

**Comment by quezak** [comment]
`NonNever` just removes keys whose value types are `never` from its argument type.

So, if you had `type Foo = { one: number; three: never }`, then `NonNever<Foo>` is just `{ one: number }`. Usually you don't use `never` as value type explicitly, so this most likely would be used in composition with other type mappers as `NonNever<SomethingThatMapsValueTypesToNever<...>>`.

The assignment from your problem is valid in typescript's structural typing, and I don't know if this can be solved completely on type level.

There is a workaround using our `Exact` type and a helper function:

```typescript
type Foo = {one: number; two: number};
type Bar = {one: number; two: number; three: number};
function exact<S, T>(obj: Exact<S, T>): T { return obj; }

const bar: Bar = { one: 1, two: 2, three: 3 }; // OK
const foo1: Foo = exact(bar); // error as expected, though the error message is not too helpful
const foo2: Foo = { one: 1, two: 2, three: 3 }; // error as expected
const foo3: Foo = { one: 1, two: 2 }; // OK
const foo4: Foo = exact({ one: 1, two: 2 }); // OK
const foo5: Foo = exact(foo3); // OK
```

The error for `foo1` is not very helpful -- but I just found [this reddit answer](https://www.reddit.com/r/typescript/comments/csf6me/typescript_match_the_exact_object_shape/exq7huv/) that has a solution for that! @krzkaczor we should incorporate the `ExtraPropertiesError` helper into our `Exact` type, WDYT?

**Comment by quezak** [comment]
I'll close this issue a problem with the NonNever type -- we can continue discussion if anyone has a better solution, or you can take it to StackOverflow :)

**Comment by krzkaczor** [comment]
Looks like you're looking for `exact` type, which is part of ts-essentials: https://github.com/krzkaczor/ts-essentials#Exact

**Comment by zanona** [comment]
Thanks a lot for the suggestion and example. I will give the `exact` type a try instead.
