### ISSUE TITLE
`next` branch future

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/ts-essentials#70]
I want to discuss here the future of `next` branch. It contains:
- `Deep` types work better with different edge cases (requires TS update)
- it supports only TS@3.5
- `DeepOmit` type

Currently `ts-essentials` work with `TS@3.2.2` or perhaps even older versions will work just fine. `next` will require using the `ts@3.5` which may be hard for some projects to support it. But frankly I have no real data about this issue, it's just my guess. 

My initial plan was to wait with releasing `next` at least for `ts@3.6` (scheduled August 2019). This would give some time for the community to migrate and of course, we would leave a readme note that there is a `2.x` release if someone uses an older ts version. Problem with this plan is obvious - new PRs would need to target both branches (or maintainers would need to cherrypick changes). This can cause a real PITA so I admit that maybe we would release `next` faster (as a major breaking change).

What do you think? Which TS version do you use? Was migration painful? 

@quezak @lucifer1004 @Andarist @ThomasdenH @macbem @alcuadrado

**Comment by quezak** [comment]
Most often I upgrade TS version in my project soon after a new version is released, and I don't remember if it ever was a pain. From my experience, if any work is needed, it's not caused by TS directly, but by some other package adopting the newly released features, for example when `jest` started using tuple types to typecheck mocked function args & returns in `.mockImplementation`, `mockReturnedValue`, etc. But in most cases, these are good changes anyway -- they lead to better typing after all :smile: 

It's only a month left until August, so we could add new features to `next` and backport fixes to `master`. On the other hand, I don't think that releasing sooner will bring much trouble -- I _hope_ people use the caret notation for dependencies (e.g. `"ts-essentials": "^2.0.8"`), so they won't get an automatic breaking changes update; while people creating new project _should_ have no reason to use an old TS version, right? Either way, I have no strong opinion towards both solutions.

**Comment by quezak** [comment]
Update: I tried adding `"typescript": "3.2.x"` and `"ts-essentials": "^3.0.0-beta.1"` to an empty project, hoping that `yarn install` will complain that `ts-essentials` has unmet requirements, but it didn't, not even a notice... is this how it should work?

When we release the 3.0 version, maybe we could attach a short message to it saying it requires TS3.5? I've seen such notices warning about breaking changes or incoming deprecations on some packages, shown in the terminal on `yarn install`.

**Comment by Andarist** [comment]
I try to upgrade as often as I can - so it's not a problem for me. IMHO you could release this soon, dont be afraid of making "breaking changes" - it's what major versions are for. With TS it's too complicated anyway - its minor versions can be breaking as is so I wouldn't worry about it here that much either.

**Comment by lucifer1004** [comment]
@krzkaczor One issue with TypeScript 3.5 I know is the Angular compiler, which will complain `The Angular Compiler requires TypeScript >=3.4.0 and <3.5.0`.

**Comment by macbem** [comment]
I second what @quezak has written. I upgrade as soon as a new TS version comes out and I've never had any issues with upgrades, so I'd release `3.0.0` sooner - there'll always be someone who's on an outdated version of TypeScript, but that doesn't mean you should wait for everyone to update their deps - especially if you don't make such breaking changes often.

**Comment by alcuadrado** [comment]
I don't upgrade that often. Mostly because I don't know how much impact that would have on my users, and don't want to release breaking major version often.

> maybe we should add TS3.5 to `peerDependencies` of the new version?

This would be problematic for people using `tsc` globally.

**Comment by kevinpeno** [comment]
We're pretty good about keeping up to date on TS at my current client and on 3.5 in most all our applications. However, we don't generally use pre-release builds (so not using `next` currently).

> `peerDependencies`
Just make sure this isn't too restrictive. Tightly coupled `peerDependencies` are a royal PITA to manage and regularly run into conflict across libs. It is understandable for this project (being compile alongside my own with TS) to need to require the right version of a compiler.

> This would be problematic for people using tsc globally.
This behavior should really stop being promoted as an option. Each project can and should attach itself to a TS version, just like you would a node version. `npx` is an option for easily running tsc on a given project (`npx tsc [options]`).

> 2.x branch support

I think it'd be good if the project contributors were willing to continue support for `2.x` branches of code for a little bit, but I can understand the hardship that presents as a small project. I'd suggest that those with vested interest in `2.x` existing (because they can't upgrade yet, etc) consider taking on this responsibility, even if it means `2.x` releases might be slower than `3.x`.

**Comment by quezak** [comment]
> Just make sure this isn't too restrictive.

We would just add `"typescript": ">=3.5.0"` and a npm install notice that you should use the old branch for older TS versions.

We'll surely continue 2.x branch support for a while -- my guess would be at least a few months, depending on how many people still use it.

**Comment by kevinpeno** [comment]
Right, that is how peer deps usually start. Then one day there is a bug in ts 3.5.8 and the parameters change. Fast forward a couple years and it's a little nuts 😬

I was mainly suggesting don't go down that route, stick with simple.

**Comment by quezak** [comment]
> I was mainly suggesting don't go down that route

I understand your points -- are there better options to ensure users have TS3.5 for our 3.x branch? I just want to avoid people coming to us saying it doesn't work, just because they missed the notice about TS version

**Comment by krzkaczor** [comment]
hanks, everyone for your input! In next couple of days, I am gonna release `next` as version 3 🎉 

It will contain `peerDependency` requirement for correct TS version. Readme will explain that older users should stick to 2.x branch.
